Flow.Web.UI/Pages/Flows.cshtml.cs
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.Interface;

namespace WFlow.Web.UI.Pages
{
    public class FlowsModel : PageModel
    {
        private readonly IFlow _service;
        private readonly IUsers _gservice;
        public ICollection<WorkFlow> flows { get; set; }

        public FlowsModel(IFlow service,
            IUsers gservice)
        {
            _service = service;
            _gservice = gservice;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                flows = await _service.GetWFlows();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditAsync(int id)
        {
            try
            {

                WorkFlow flow = new WorkFlow();
                var depts = await _gservice.GetDepartmentsList();
                flow.DepartmentIEnumerable = depts;
                if (id == 0)
                {
                    return Partial("_AddEditFlow", flow);
                }

                flow = await _service.GetSingleFlow(id);
                flow.DepartmentIEnumerable = depts;
                return Partial("_AddEditFlow", flow);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveAsync(WorkFlow flow)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await _service.AddEditFlow(flow);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }

    }
}

Flow.Web.UI/Pages/Users.cshtml.cs
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.Interface;

namespace Flow.Web.UI.Pages
{
    public class UsersModel : PageModel
    {
        private readonly IUsers usersService;
        public ICollection<User> Users { get; set; }
        public ICollection<Department> Departments { get; set; }
        public ICollection<AppWorkFlow.Data.Entity.WorkFlow> flows { get; set; }

        public UsersModel(IUsers _usersService)
        {
            usersService = _usersService;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Users = await usersService.GetUsers();
                Departments = await usersService.GetDepartmentsList();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditUserAsync(int userid)
        {
            try
            {

                User user = new User();
                if (userid == 0)
                {
                    return Partial("_AddEditUser", user);
                }

                user = await usersService.GetSingleUser(userid);
                return Partial("_AddEditUser", user);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveUserAsync(User user)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.AddEditUser(user);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostRemoveUserAsync(int userid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.RemoveUser(userid);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }
        }


        public async Task<IActionResult> OnGetDepartmentsAsync()
        {
            try
            {
                Departments = await usersService.GetDepartmentsList();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditDepartmentAsync(int id)
        {
            try
            {

                Department department = new Department();
                var users = await usersService.GetUsers();
                department.UsersEnumerable = users;
                if (id == 0)
                {
                    return Partial("_AddEditDepartment", department);
                }

                department = await usersService.GetSingleDepartment(id);
                department.UsersEnumerable = users;
                return Partial("_AddEditDepartment", department);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveDepartmentAsync(Department department)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.AddEditDepartment(department);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
    }
}

Flow.Web.UI/Pages/Shared/_AddEditDepartment.cshtml
@model AppWorkFlow.Data.Entity.Department

<form class="kt-form kt-form--label-right" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="kt-portlet__body">
        <div class="form-group row">

            <div class="col-lg-12">
                <label>Name:</label>
                <input asp-for="Name" required class="form-control">
            </div>
            <div class="col-lg-12">
                <label>Description:</label>
                <input asp-for="Description" required class="form-control">
            </div>
            <div class="col-lg-12">
                <label>Department Head:</label>
                <select required asp-for="UserHeadId" class="form-control" asp-items="@(new SelectList(Model.UsersEnumerable, "Id", "Name"))">
                </select>
            </div>
        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <div class="row">
                <div class="col-lg-6">
                    <button id="btnPost" asp-page="/users" asp-page-handler="SaveDepartment" type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

Flow.Web.UI/Pages/Shared/_AddEditFlow.cshtml
@model AppWorkFlow.Data.Entity.WorkFlow

<form class="kt-form kt-form--label-right" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="kt-portlet__body">
        <div class="form-group row">

            <div class="col-lg-12">
                <label>Name:</label>
                <input asp-for="Name" required class="form-control">
            </div>
            <div class="col-lg-12">
                <label>Details:</label>
                <input asp-for="Details" required class="form-control">
            </div>
            <div class="col-lg-12">
                <label>Group:</label>
                <select required asp-for="DepartmentId" class="form-control" asp-items="@(new SelectList(Model.DepartmentIEnumerable, "Id", "Name"))">
                </select>
            </div>
        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <div class="row">
                <div class="col-lg-6">
                    <button id="btnPost" asp-page="/flows" asp-page-handler="Save" type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

Flow.Web.UI/Pages/Shared/_AddEditRequest.cshtml
@model AppWorkFlow.Data.Entity.FlowRequest

<form class="kt-form kt-form--label-right" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="IsNewRequest" />

    <div class="kt-portlet__body">
        <div class="form-group row">

            <div class="col-lg-12">
                <label>Name:</label>
                <input asp-for="Name" required class="form-control">
            </div>

            <div class="col-lg-12">
                <label>Group:</label>
                <select required asp-for="WorkFlowId" class="form-control" asp-items="@(new SelectList(Model.EnumerableWorkFlows, "Id", "Name"))">
                </select>
            </div>
        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <div class="row">
                <div class="col-lg-6">
                    <button id="btnPost" asp-page="/requests" asp-page-handler="Save" type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

Flow.Web.UI/Pages/Shared/_AddEditUser.cshtml
@model AppWorkFlow.Data.Entity.User

<form class="kt-form kt-form--label-right" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="kt-portlet__body">
        <div class="form-group row">

            <div class="col-lg-12">
                <label>Name:</label>
                <input asp-for="Name" required class="form-control">
            </div>
            <div class="col-lg-12">
                <label>Title:</label>
                <input asp-for="Title" required class="form-control">
            </div>

        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <div class="row">
                <div class="col-lg-6">
                    <button id="btnPost" asp-page="/users" asp-page-handler="SaveUser" type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

Flow.Web.UI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flow.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Flow.Web.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/flows">WorkFlow</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/requests">Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/departmentrequests">Request Actions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal fade text-left" id="FormModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="title" class="modal-title"></h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="FormModelDiv">

                </div>

            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WorkFlow - By Haitham Ahmed <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Flow.Web.UI/Pages/Shared/_SetRequestAction.cshtml
@*@model AppWorkFlow.Data.Entity.FlowRequestAction*@
@model WFlow.Core.DTO.RequestActionDTO

<form class="kt-form kt-form--label-right" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="FlowRequestId" />

    <div class="kt-portlet__body">
        <div class="form-group row">


            <div class="col-lg-12">
                <label>Action:</label>
                <select required asp-for="RequestStatus" class="form-control" asp-items="@Html.GetEnumSelectList<AppWorkFlow.Core.Enums.FlowAction>()">
                </select>
            </div>

            <div class="col-lg-12">
                <label>Redirect To:</label>
                <select required asp-for="RedirectToDepartmentId" class="form-control" asp-items="@(new SelectList(Model.DepartmentEnumerable, "Id", "Name"))">
                </select>
            </div>
        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <div class="row">
                <div class="col-lg-6">
                    <button id="btnPost" asp-page="/departmentRequests" asp-page-handler="Save" type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>