Flow.Web.UI/Pages/DepartmentRequests.cshtml.cs
using AppWorkFlow.Core;
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.DTO;
using WFlow.Core.Interface;

namespace WFlow.Web.UI.Pages
{
    public class DepartmentRequestsModel : PageModel
    {
        private readonly IUsers usersService;
        private readonly IFlowRequests requestsService;
        private readonly IFlow flowsService;
        public ICollection<User> Users { get; set; }
        public IEnumerable<Department> DepartmentEnumerable { get; set; }
        public DepartmentRequestsModel(IUsers _usersService,
            IFlowRequests _requestsService,
            IFlow _flowsService)
        {
            usersService = _usersService;
            requestsService = _requestsService;
            flowsService = _flowsService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Users = await usersService.GetUsers();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }

        public async Task<IActionResult> OnGetSubmitActionAsync(int id, int frid)
        {
            try
            {
                RequestActionDTO flowRequestAction = new RequestActionDTO
                {
                    Id = id,
                    FlowRequestId = frid,
                    DepartmentEnumerable = await usersService.GetDepartmentsList()
                };

                return Partial("_SetRequestAction", flowRequestAction);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveAsync(RequestActionDTO flowRequestActionDto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                FlowRequestAction flowRequestAction = new FlowRequestAction
                {
                    RequestStatus = flowRequestActionDto.RequestStatus,
                    FlowRequestId = flowRequestActionDto.FlowRequestId
                };
                var actionstatus = (Enums.FlowAction)int.Parse(flowRequestActionDto.RequestStatus);
                if (actionstatus.ToString().Equals(Enums.FlowAction.Redirect.ToString()))
                {
                    flowRequestAction.RedirectToDepartmentId = flowRequestActionDto.RedirectToDepartmentId;
                }

                flowRequestAction.ActionDate = DateTime.UtcNow.AddHours(3);


                int i = await requestsService.SetFlowRequestAction(flowRequestAction);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }

    }
}

Flow.Web.UI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Flow.Web.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Flow.Web.UI/Pages/Flows.cshtml.cs
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.Interface;

namespace WFlow.Web.UI.Pages
{
    public class FlowsModel : PageModel
    {
        private readonly IFlow _service;
        private readonly IUsers _gservice;
        public ICollection<WorkFlow> flows { get; set; }

        public FlowsModel(IFlow service,
            IUsers gservice)
        {
            _service = service;
            _gservice = gservice;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                flows = await _service.GetWFlows();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditAsync(int id)
        {
            try
            {

                WorkFlow flow = new WorkFlow();
                var depts = await _gservice.GetDepartmentsList();
                flow.DepartmentIEnumerable = depts;
                if (id == 0)
                {
                    return Partial("_AddEditFlow", flow);
                }

                flow = await _service.GetSingleFlow(id);
                flow.DepartmentIEnumerable = depts;
                return Partial("_AddEditFlow", flow);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveAsync(WorkFlow flow)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await _service.AddEditFlow(flow);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }

    }
}

Flow.Web.UI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Flow.Web.UI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Flow.Web.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Flow.Web.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Flow.Web.UI/Pages/Requests.cshtml.cs
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.Interface;

namespace WFlow.Web.UI.Pages
{
    public class RequestsModel : PageModel
    {
        private readonly IFlow _service;
        private readonly IUsers _gservice;
        public ICollection<FlowRequest> FlowRequests { get; set; }

        public RequestsModel(IFlow service,
            IUsers gservice)
        {
            _service = service;
            _gservice = gservice;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                FlowRequests = await _service.GetWFlowRequests();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }

        public async Task<IActionResult> OnGetAddEditAsync(int id)
        {
            try
            {

                FlowRequest flowrequests = new FlowRequest();
                var flows = await _service.GetWFlows();
                flowrequests.EnumerableWorkFlows = flows;
                flowrequests.RequestDate = DateTime.UtcNow.AddHours(3);
                flowrequests.IsNewRequest = true;
                if (id == 0)
                {
                    return Partial("_AddEditRequest", flowrequests);
                }

                flowrequests = await _service.GetSingleFlowRequest(id);
                flowrequests.EnumerableWorkFlows = flows;
                return Partial("_AddEditRequest", flowrequests);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveAsync(FlowRequest flowRequest)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await _service.AddEditFlowRequest(flowRequest);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
    }
}

Flow.Web.UI/Pages/Users.cshtml.cs
using AppWorkFlow.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WFlow.Core.Interface;

namespace Flow.Web.UI.Pages
{
    public class UsersModel : PageModel
    {
        private readonly IUsers usersService;
        public ICollection<User> Users { get; set; }
        public ICollection<Department> Departments { get; set; }
        public ICollection<AppWorkFlow.Data.Entity.WorkFlow> flows { get; set; }

        public UsersModel(IUsers _usersService)
        {
            usersService = _usersService;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Users = await usersService.GetUsers();
                Departments = await usersService.GetDepartmentsList();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditUserAsync(int userid)
        {
            try
            {

                User user = new User();
                if (userid == 0)
                {
                    return Partial("_AddEditUser", user);
                }

                user = await usersService.GetSingleUser(userid);
                return Partial("_AddEditUser", user);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveUserAsync(User user)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.AddEditUser(user);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostRemoveUserAsync(int userid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.RemoveUser(userid);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }
        }


        public async Task<IActionResult> OnGetDepartmentsAsync()
        {
            try
            {
                Departments = await usersService.GetDepartmentsList();
                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }

        }
        public async Task<IActionResult> OnGetAddEditDepartmentAsync(int id)
        {
            try
            {

                Department department = new Department();
                var users = await usersService.GetUsers();
                department.UsersEnumerable = users;
                if (id == 0)
                {
                    return Partial("_AddEditDepartment", department);
                }

                department = await usersService.GetSingleDepartment(id);
                department.UsersEnumerable = users;
                return Partial("_AddEditDepartment", department);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
        public async Task<IActionResult> OnPostSaveDepartmentAsync(Department department)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToPage();
                }

                int i = await usersService.AddEditDepartment(department);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToPage();
            }

        }
    }
}

Flow.Web.UI/Pages/DepartmentRequests.cshtml
@page
@model WFlow.Web.UI.Pages.DepartmentRequestsModel
@{
    ViewData["Title"] = "DepartmentRequests";
    var cntlname = ViewContext.RouteData.Values["Page"].ToString();

}

<h1>Manage Requests</h1>
<div>

    <p>@Html.ValidationSummary(false)</p>
    <table class="table  table-borderless ">
        <thead>
            <tr>
                <td>Name</td>
                <td>Title</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Users)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Title</td>
                    <td>
                        @await Component.InvokeAsync("NewRequests", new { userid = @item.Id })
                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>

Flow.Web.UI/Pages/Flows.cshtml
@page
@model WFlow.Web.UI.Pages.FlowsModel
@{
    ViewData["Title"] = "Users";
    var cntlname = ViewContext.RouteData.Values["Page"].ToString();

}
<div>
    <h1>WorkFlow</h1>
    <button type="button" onclick="AddEditForm(0,'@cntlname','AddEdit','id')" class="btn btn-sm btn-warning ">New</button>
    <p>@Html.ValidationSummary(false)</p>
    <table class="table table-hover table-borderless table-striped">
        <thead>
            <tr>
                <td>Name</td>
                <td>Details</td>
                <td>Department In Charge</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.flows)
            {
            <tr>
                <td>@item.Name</td>
                <td>@item.Details</td>
                <td>@item.Department.Name</td>
                <td>
                    <div class="btn-group " role="group">
                        <button type="button" onclick="AddEditForm(@item.Id,'@cntlname','AddEdit','id')" class="btn btn-sm btn-warning ">edit</button>|
                    </div>
                </td>
            </tr>

            }

        </tbody>
    </table>

</div>

Flow.Web.UI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>WorkFlow</p>
    </div>

Flow.Web.UI/Pages/Requests.cshtml
@page
@model WFlow.Web.UI.Pages.RequestsModel
@{
    ViewData["Title"] = "requests";
    var cntlname = ViewContext.RouteData.Values["Page"].ToString();
}
<div>
    <h1>Requests</h1>
    <button type="button" onclick="AddEditForm(0,'@cntlname','AddEdit','id')" class="btn btn-sm btn-warning ">New</button>
    <p>@Html.ValidationSummary(false)</p>
    <table class="table table-hover table-borderless table-striped">
        <thead>
            <tr>
                <td>Name</td>
                <td>Request Type</td>
                <td>Head Of Flow</td>
                <td>Status</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.FlowRequests)
            {
            <tr>
                <td>@item.Name</td>
                <td>@item.WorkFlow.Name</td>
                <td>@item.WorkFlow.Department.UserHead.Name</td>
                <td>
                    @if (item.IsClosed)
                    {
                        <h6 class="text-success">Closed</h6>
                    }
                    else
                    {
                        if (item.IsNewRequest)
                        {
                            <h6 class="text-info">New</h6>
                        }
                        else
                        {
                            <h6 class="text-warning">Pending</h6>
                        }

                    }

                </td>
                <td>
                    @{
                        var actions = item.RequestActions
                        .Where(x => x.Id == item.CurrentFlowRequestActionId.Value).ToList();
                    }
                    @if (actions.Where(x => x.RequestStatus.Equals(Enums.FlowAction.Accept.ToString())).Count() > 0)
                    {
                        <h6 class="text-success">Accepted</h6>
                    }
                    else if (actions.Where(x => x.RequestStatus.Equals(Enums.FlowAction.Reject.ToString())).Count() > 0)
                    {
                        <h6 class="text-danger">Rejected</h6>
                    }
                    else
                    {
                        <h6 class="text-info">In Progress</h6>
                    }
                </td>
                <td>
                    @if (item.IsNewRequest)
                    {
                        <div class="btn-group " role="group">
                            <button type="button" onclick="AddEditForm(@item.Id,'@cntlname','AddEdit','id')" class="btn btn-sm btn-warning ">edit</button>
                        </div>
                    }

                </td>
            </tr>

            }

        </tbody>
    </table>

</div>

Flow.Web.UI/Pages/Users.cshtml
@page
@model Flow.Web.UI.Pages.UsersModel
@{
    ViewData["Title"] = "Users";
    var cntlname = ViewContext.RouteData.Values["Page"].ToString();

}
    
    <div id="accordion">
        <div class="card">
            <div class="card-header alert-success" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseuser" aria-expanded="true" aria-controls="collapseuser">
                        Users
                    </button>
                </h5>
            </div>
            <div id="collapseuser" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <div>
                         
                        <button type="button" onclick="AddEditForm(0,'@cntlname','AddEditUser','userid')" class="btn btn-sm btn-warning ">New</button>
                        <p>@Html.ValidationSummary(false)</p>
                        <table class="table table-hover table-borderless table-striped">
                            <thead>
                                <tr>
                                    <td>Name</td>
                                    <td>Title</td>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Users)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td>@item.Title</td>
                                        <td>
                                            <div class="btn-group " role="group">
                                                <button type="button" onclick="AddEditForm(@item.Id,'@cntlname','AddEditUser','userid')" class="btn btn-sm btn-warning ">edit</button>|
                                                <form method="post"><button type="submit" asp-page-handler="RemoveUser" asp-route-userid="@item.Id" class="btn btn-sm btn-danger">Remove</button></form>
                                            </div>
                                        </td>
                                    </tr>

                                }

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header alert-warning" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFlow" aria-expanded="true" aria-controls="collapseFlow">
                        Departments
                    </button>
                </h5>
            </div>
            <div id="collapseFlow" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <div>
                      
                        <button type="button" onclick="AddEditForm(0,'@cntlname','AddEditDepartment','id')" class="btn btn-sm btn-warning ">New</button>
                        <p>@Html.ValidationSummary(false)</p>
                        <table class="table table-hover table-borderless table-striped">
                            <thead>
                                <tr>
                                    <td>Name</td>
                                    <td>Title</td>
                                    <td>Head</td>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Departments)
                                {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Description</td>
                                    <td>@item.UserHead.Name</td>
                                    <td>
                                        <div class="btn-group " role="group">
                                            <button type="button" onclick="AddEditForm(@item.Id,'@cntlname','AddEditDepartment','id')" class="btn btn-sm btn-warning ">edit</button>|
                                        </div>
                                    </td>
                                </tr>

                                }

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>